### ISSUE TITLE
Public place to see people who have signed

### ISSUE THREAD

**Issue by cheerfulstoic** [dear-github/dear-github#108]
For a group that is complaining about openness it felt weird filling out a form to "sign" this

**Comment by dmethvin** [comment]
What would be a better way?

**Comment by cheerfulstoic** [comment]
Oh, sorry, I didn't see the link to the spreadsheet.  I had just clicked the "Please sign here" and thought that the results were private.  What you have is great, thanks!

Any word from GitHub?
