### ISSUE TITLE
Watch only for release tags

### ISSUE THREAD

**Issue by da-x** [dear-github/dear-github#111]
Let me watch a repository, but notify me about releases made.

**Comment by james2doyle** [comment]
I currently use IFTTT to do this, but I use the ATOM feed that appears on all release pages.

So you can use https://github.com/da-x/git-bottle/releases.atom as the feed, then have it email you.

It would be nice to have native support for this.

**Comment by jawshooah** [comment]
:+1:

**Comment by tux-00** [comment]
:+1

**Comment by TPS** [comment]
Quite similar to https://github.com/isaacs/github/issues/410

**Comment by janos** [comment]
Hi, I’ve created the project of my own, that enables notifications to your email and/or Slack account from GitHub and 8 more other programming platforms. Check it out here: https://newreleases.io. Hope it helps.

**Comment by VojtechVitek** [comment]
I have an opposite request. I'd like to unfollow automated releases from our merge bot. And still watch everything else.

**Comment by slel** [comment]
GitHub now offers to watch releases only!

**Comment by da-x** [comment]
True. It's accessible from the 'Watch' drop-down.

**Comment by janos** [comment]
It appears that "watch releases only" doesn't follow tags and many projects use only tags for announcing new versions. While https://newreleases.io sends notifications for tags too, it also has several version filtering options, based on regex expressions, pre and updated releases. It also offers email frequency options.

**Comment by timkofu** [comment]
> It appears that "watch releases only" doesn't follow tags and many projects use only tags for announcing new versions.

Including [CPython](https://github.com/python/cpython/releases), and it would be great to know when a new release is made.

**Comment by h-vetinari** [comment]
I opened a new issue for subscribing to tags (despite this issue being closed, it's only possible to follow "releases", and not "tags"): #399

**Comment by brianjmurrell** [comment]
> Hi, I’ve created the project of my own, that enables notifications to your email and/or Slack account from GitHub and 8 more other programming platforms. Check it out here: https://newreleases.io. Hope it helps.

I've been using that, but honestly, it's too many clicks from the e-mail I get to the being able to see what's new in the release.
