### ISSUE TITLE
pull request without spam-merge commit

### ISSUE THREAD

**Issue by denji** [dear-github/dear-github#119]
We would like to accept pull request button without spam 2th commit, "review" and the "author" of a commit can be set. The replacement of the commit message will also be useful if we want to merge the changes in 1 cherry-pick or merge several.

```bash
GIT_COMMITTER_NAME="Review Name";
GIT_AUTHOR_NAME="Author Name";
GIT_COMMITTER_EMAIL="Email Review";
GIT_AUTHOR_EMAIL="Email Author";
```

![shopify-history](https://cloud.githubusercontent.com/assets/3759759/13023357/c7a91cc8-d1f0-11e5-8b88-1963dac1ae51.png)

#### Reference
* https://help.github.com/articles/closing-issues-via-commit-messages/
* https://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/

**Comment by andschwa** [comment]
:+1: This one is an absolute necessity if you maintain a project that actively uses submodules. One can argue `git subtree` is better... but that point is moot if you have to be able to replace the module without affecting the superproject (copyright issues etc.).

It's a major PITA to force my team to rebase and submodule bump, then `--ff-only merge` from the CLI. Means I (the maintainer) ends up manually merging most things to avoid trouble with submodules getting extraneous commits.

**Comment by jsvgoncalves** [comment]
+1

**Comment by untitaker** [comment]
This is especially annoying with protected branches. In order for the PR to be mergeable, the branch must be up-to-date with master, however, GitHub's UI only allows the user to merge master into their branch as a form of updating. There's no way to rebase.

There should be a per-repo setting for preferring rebase over merge.

**Comment by denji** [comment]
https://github.com/blog/2141-squash-your-commits

**Comment by andschwa** [comment]
That is unfortunately still not we need for projects with active submodules. We just want a `--ff-only` merge option (without squashing).
