### ISSUE TITLE
Add signed commit badges/veification

### ISSUE THREAD

**Issue by Qix-** [dear-github/dear-github#122]
Please, please please show a badge or something next to [signed commits](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work).

As if this isn't [already an issue](https://web.archive.org/web/20160119122717/https://github.com/mayuso/JavaDataMining/issues/29), it's recently been pointed out that [anyone can fake commit authors](https://github.com/jayphelps/git-blame-someone-else/commit/e5cfe4bb2190a2ae406d5f0b8f49c32ac0f01cd7) and make them look terrifyingly _real_.

---

Side note: developers, [start signing your commits](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work).

**Comment by joshmanders** [comment]
Dupe of #89 but agreed. I've been actively posting issues on repos where people do this.

https://github.com/NikolayIT/ASP.NET-MVC-Template/issues/1

https://github.com/KubaKaszycki/libMhO/issues/2

https://github.com/MichalPaszkiewicz/inknote/issues/21

**Comment by Qix-** [comment]
Not a dupe. I'm referring to tags/commits signed using a private certificate. Currently, a user doesn't even have to be added to a repository for me to push commits "made" by them.

[Case and point @joshmanders](https://github.com/Qix-/josh-manders-made-this).

**Comment by Qix-** [comment]
That's not to say #89 is a huge problem right now.

**Comment by denji** [comment]
GPG will be help with possible adding as trusted github gpg-pubkey.

**Comment by joshmanders** [comment]
Sorry @Qix- dupe was the wrong word, as my issue wasn't about gpg signing, but about the second half. Both of these go together.

In any case, I do steal candy from babies, so I find that repo hard to refute as being committed to by me.

**Comment by joshmanders** [comment]
Fun fact, while it does show I committed that commit on the repo, it doesn't show up in any of my profile activity though, so they use more under the hood, so it shouldn't be hard for them to distinguish who committed what.

**Comment by Qix-** [comment]
Yeah I noticed that too. Kinda weird.

Also taking candy from babies is rude. Yeesh. :candy:

**Comment by joshmanders** [comment]
> Also taking candy from babies is rude. Yeesh. :candy:

Don't want them to rot their teefs.

**Comment by Qix-** [comment]
Oh man, you're totally right. Never thought of it that way. And the early onset diabetes they could develop? Not good.

Gentleman and scholar, you are. :+1: :tophat:

**Comment by joshmanders** [comment]
More fun today. 

https://github.com/flextry/Telerik-Academy/pull/1

**Comment by joshmanders** [comment]
Another day, another spammer.

https://github.com/joni2back/angular-filemanager/issues/116

**Comment by alferov** [comment]
It's not the very first spam from him, it started last year :rage1: 
https://github.com/joni2back/angular-filemanager/issues/59

**Comment by joshmanders** [comment]
He even deletes the contents of the issue and renames it so that it doesn't show up if anyone looks at it. I've reverted it back.

**Comment by aensley** [comment]
The spamming is another reason #128 or #129 would be nice.

**Comment by joshmanders** [comment]
Either I am banned or he deleted everything because I'm getting 404's on everything.

**Comment by jawshooah** [comment]
You're banned, I can still see it.

**Comment by joshmanders** [comment]
I've checked with many sources and they all said they get 404's also.

**Comment by jawshooah** [comment]
My bad, just checked on my laptop and I'm getting the same. Android app must have cached it.

**Comment by joshmanders** [comment]
Just a side note, this whole thread is strangely more Josh oriented than any other name.

**Comment by joshmanders** [comment]
Yay more fucktardery. https://github.com/KubaKaszycki/libMhO/issues/3

**Comment by joshmanders** [comment]
I highly encourage everyone here to report these users for abuse: https://github.com/contact?report=<github_username>

**Comment by joshmanders** [comment]
@Qix- we got signed commit verification. https://github.com/blog/2144-gpg-signature-verification

**Comment by Qix-** [comment]
Huh. Way to go Github. Thanks @joshmanders.
