### ISSUE TITLE
Multiple Assignees

### ISSUE THREAD

**Issue by jackpoz** [dear-github/dear-github#131]
Some long and complex issues require more than a single assignee to work on, it would be a nice feature if it was possible to set multiple assignees to GitHub Issues. This is also useful for large open source teams where a developer would like to express his "I want to help solving this issue!" will, without removing the current assignee.

**Comment by aensley** [comment]
I like the concept, but it seems like it would be problematic in practice. There would still need to be a way to designate the "Primary" assignee; the one person ultimately responsible for the Issue's progress at the moment.

As it is right now, tagging people makes them a participant, subscribes them to all events in an Issue/PR, and shows them in the participant list. And the "primary" assignee is the person actually assigned. For my team's uses, that's sufficient.

It would be nice to have something that differentiated between the different types of participants though, separating spectators from the people responsible for the issue. I think that's what you're getting at, and I like that.

**Comment by jackpoz** [comment]
I can provide https://github.com/TrinityCore/TrinityCore/issues/15075 as example: me and the author of the issue started working together on the feature to be implemented since day 1, brainstorming and writing together its  specs.
Due to the usual life constraints (work, school/uni, etc) he has little time to work on and is currently providing only feedback on the code I write and push. Next week/month it could be the other way around, with me having little time available and him being able to work on it.
It really feels like there's not just 1 developer assigned to the issue but a team (of 2 for now). I would like for example to find this issue when searching with "assignee:jackpoz" query, as he would too.

I understand the current behavior is sufficient for most cases where the "manager" assigns issues, I use github mostly with teams where every developer picks up what he wants to work on without a manager :)

Please note this is just a suggestion following the recent very much appreciated issue_template.md feature, I have no clue whether it's easy or impossible to implement. Even if it gets closed/rejected I'll still continue to provide my feedback as GitHub user :)

**Comment by aensley** [comment]
The search thing makes perfect sense. I'm just a regular user like you, providing my $0.02.

I like this idea.

**Comment by jackpoz** [comment]
https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests thank you!

**Comment by Tyriar** [comment]
\\(^_^)/
