### ISSUE TITLE
Allow to download file instead of raw render

### ISSUE THREAD

**Issue by KonradIT** [dear-github/dear-github#132]
I manage a repo called Autoexechack, this is a repository filled with scripts for an action camera brand. Its very inconvenient to right click RAW and save, because it overrides the original format and also sometimes it adds a .txt at the end.

**Add a download button next to RAW in a file to download it directly**

Kind of like this:

![](http://i.imgur.com/KhgCqi8.png?1)

**Comment by koenpunt** [comment]
I think they intentionally left out the file type, to prevent GitHub being used as a cdn. http://rawgit.com was introduced for that purpose, although I don't think they're affiliated to GitHub
