### ISSUE TITLE
Add issue templates on Github Enterprise

### ISSUE THREAD

**Issue by jiyeonseo** [dear-github/dear-github#146]
I love to use a template in making issues and pull request.
I'd like to use this feature with collaborator in my company.
Could you add issue and pull request template on Github Enterprise?! :heart_eyes_cat:

related issue #72

**Comment by elfinxx** [comment]
+1

**Comment by pmn** [comment]
Hi @jiyeonseo -- Issue and Pull Request templates are available in [GitHub Enterprise 2.6](https://enterprise.github.com/releases/2.6.0), which was released last month.

**Comment by ikhoon** [comment]
👍

**Comment by kyeok** [comment]
❤️

**Comment by myriky** [comment]
cheese 🍰  👍
