### ISSUE TITLE
Mark comments as resolved

### ISSUE THREAD

**Issue by jeroenvisser101** [dear-github/dear-github#154]
It would be nice if we could have an option to mark comments on PRs as resolved so they'd be collapsed or dimmed.

**Comment by jeroenvisser101** [comment]
This is done!

**Comment by AmatanHead** [comment]
Sorry to bring this up. Maybe I'm missing something.
This issue is closed but I don't see how can I mark comments as resolved...

**Comment by fritzo** [comment]
The only options on the github gui are 'add a reaction', 'change', and 'delete'. There is no 'resolve'.

**Comment by jeroenvisser101** [comment]
Since only reviews can be marked as resolved, I guess this is still pending.

**Comment by ourownstory** [comment]
Yes, this simple feature would greatly speed up my workflow when resolving comments!

**Comment by aspiers** [comment]
As with many other issues in this repository, this is a duplicate of an issue already filed in `isaacs/github`:

- [Mark an conversation on a diff as resolved · Issue #251 · isaacs/github](https://github.com/isaacs/github/issues/251)

**Comment by koenpunt** [comment]
Comments on issues can be marked as resolved as of not too long ago

**Comment by aspiers** [comment]
[**@koenpunt**](https://github.com/koenpunt) commented on [1 Aug 2018, 21:00 BST](https://github.com/dear-github/dear-github/issues/154#issuecomment-409702767 "2018-08-01T20:00:52Z - Replied by Github Reply Comments"):
> Comments on issues can be marked as resolved as of not too long ago

True but this is missing lots more details, which are covered in [the issue of which this is a duplicate](https://github.com/isaacs/github/issues/251#issuecomment-408858652).

IMHO this is another example of many that this repository is damaging the GitHub community by unnecessarily fragmenting it.  I have [tried to help fix that](https://github.com/dear-github/dear-github/pull/295) but unfortunately my PR has been ignored.

**Comment by jeroenvisser101** [comment]
I'm going to close this as I don't think GitHub will (in the short term) be adding this and because the current features already allow more then when this was opened. Should anyone have a different opinion, they can raise their own issue.
