### ISSUE TITLE
Ability to use Tab in pull requests comments

### ISSUE THREAD

**Issue by gyzerok** [dear-github/dear-github#155]
Hi, dear GitHub!

I am always happy to work with you. And I really excited with number of cool usability features you released in the last months.

However there is one thing which makes me struggle multiple times during every day development. This is inability to use Tab in comments in pull request review process. I always try to provide some code samples to my teammates about how to do some stuff in another way and tend to hit space key infinitely during the process.

I should always mention that in gists this works perfectly and it looks like desired behaviour for me.

**Comment by laughedelic** [comment]
JFYI, This is covered by the [refined-github](https://github.com/sindresorhus/refined-github) chrome extension.

**Comment by fobos** [comment]
@laughedelic what if i'm using Opera, FF or Safari?

**Comment by laughedelic** [comment]
@fobos then no luck for you... 😛 
I just posted this for those interested in a temporary and _partial_ solution. I'm completely support this request.

**Comment by laughedelic** [comment]
@fobos btw, it has a [Safari version](https://github.com/fantattitude/refined-github-safari) 😉

**Comment by koenpunt** [comment]
The difference with gists is that it's using a code-editor, whereas comment are plain textareas. Although it might be possible that when in a code block, tabbing is supported. 
But comments are still just comments, and using tab to proceed to the next input or button is expected and desired.
