### ISSUE TITLE
Why was the Contribution Streak (days-in-a-row) Removed...?!

### ISSUE THREAD

**Issue by nelsonic** [dear-github/dear-github#163]
Was it costing GitHub too much money to render the numbers blow the contribution chart...?
Or did someone *complain* that it was taking up too much space in the UI...?

![contribution-activity-chart](https://cloud.githubusercontent.com/assets/194400/15414058/cc4024a4-1e2e-11e6-9572-102f70284510.png)

Why _remove_ a feature that was working and added "Gamification" to the site?

**Comment by laughedelic** [comment]
Probably because of this? http://erik.io/blog/2016/04/01/how-github-contribution-graph-is-harmful/

**Comment by nelsonic** [comment]
Yeah, there have been similar posts over the years by people who have given up on achieving *mastery* in their craft (coding) ... didn't expect GitHub to Globally disable the feature for *everyone*. Fail.
It's impressive that 595 Thumbs-ups have "spoken" for a community of Millions of people...
Oh well.

**Comment by ocdtrekkie** [comment]
I am incredibly disappointed in GitHub making this decision. I used it to encourage me to write code every day, as a hobby.

**Comment by koenpunt** [comment]
With a streak of 640 days, wouldn't you think it's time for a few days off?

**Comment by ocdtrekkie** [comment]
@koenpunt You'd be making the mistake of assuming that he considers it work. Or that he needs time off from it. Plenty of us just love working with our computers.

**Comment by laughedelic** [comment]
> I used it to encourage me to write code every day, as a hobby.

@ocdtrekkie only the number works for you? you still have the coloured squares and breaking a streak is quite obvious.

**Comment by nelsonic** [comment]
@koenpunt I have 3 weeks "off" planned with family in July, thanks for asking. 🌅 
Is that going to stop me from writing a few line of code each day before anyone wakes up because I *want* to keep improving? nope. As hard as it may be to believe, some people actually *enjoy* coding when they aren't being paid. others realise that if they want to "get good" they have to *practice*... 

> Just like the kid who wants to give up playing the musical instrument or practicing the sport because its "too hard", sometimes a little encouragement is required to ensure perseverance.

**Comment by nelsonic** [comment]
Found the answer. https://github.com/isaacs/github/issues/627#issuecomment-220642794
Two fine & wise gentlemen (@aaron-em @johnstt) pointed me in the right direction.
Case closed. ✅

**Comment by Naramsim** [comment]
https://github.com/Naramsim/GithubOriginalStreak
Get it back if you want

**Comment by koenpunt** [comment]
@ocdtrekkie @nelsonic Just saying that taking sometime off of coding is generally good to reflect on things.

**Comment by ocdtrekkie** [comment]
@koenpunt I don't disagree. But I don't see why that's relevant to the fact that some people enjoy this metric as a motivational tool.

**Comment by contracode** [comment]
Thanks for the share @Naramsim !!!

**Comment by elie222** [comment]
Why was "Repositories Contributed" to removed? (Would prefer not to open a new issue and start a whole new shouting match. I assume someone's already asked it and I'm just not finding the Github issue for it.)

**Comment by 60noypearl** [comment]
I think that it won't solve the problem of people faking code in GitHub.
Sure, there was a problem that people faked contributions in order to have a long streak, but I am sure that these same people fake other things- like pushing code that isn't theirs in order to have a rich activity. Preventing all the users from gaining so much from the streak feature won't solve the problem and is harmful.

**Comment by ohjames** [comment]
I'm glad it was removed ;)

**Comment by AtomicNess123** [comment]
> I am incredibly disappointed in GitHub making this decision. I used it to encourage me to write code every day, as a hobby.

@ocdtrekkie Honestly, if you don't get any other means to be encouraged but showing off to the world, look into that, brother. Into the real deep reason why you code... maybe it's not your passion, but your show off.

**Comment by rt-hamilton** [comment]
Research has been done on the influence of the streak feature (and its removal): https://arxiv.org/pdf/2006.02371.pdf by https://github.com/lukasmoldon/GHStreaksThesis

**Comment by pfalcon** [comment]
> Honestly, if you don't get any other means to be encouraged but showing off to the world, look into that, brother. Into the real deep reason why you code... maybe it's not your passion, but your show off.

Maybe some people want to show off to themselves. Maybe some people brush their hair in the morning so they felt ok about themselves, and not to please strangers they meet on the streets, shops, offices. Other people are such enigmas, that some of us will never understand them, always judging them by ourselves.

Anyway, why I write - a few minutes ago, @rt-hamilton posted a link to https://github.com/lukasmoldon/GHStreaksThesis as a kind of "scientific evidence" on the matter. And minutes later, the comment is not here. @rt-hamilton, any chance you removed the comment yourself, or is it some kind of censorship in this repo?

**Comment by rt-hamilton** [comment]
I indeed deleted it and posted it instead [here](https://github.com/isaacs/github/issues/627), didnt want to spam 😄 - so no censorship in this case 

My original message:
_Research has been done on the influence of the streak feature (and its removal): https://arxiv.org/pdf/2006.02371.pdf by https://github.com/lukasmoldon/GHStreaksThesis_
