### ISSUE TITLE
Incorrect behaviour in download process by HTTP/1.0 UserAgents

### ISSUE THREAD

**Issue by Perlover** [dear-github/dear-github#178]
Hi,

I researched Github problem. If you will try download now zip/tar.gz archives by wget program ('HTTP/1.0' useragent) - now first time you will get bad zip archive because file will have hex_size\r\n in begining (from chunked encoding). It's big problem because tar.gz downloading used by many scripts. I cannot install servers now because now your servers work bad.

You server codeload.github.com when to be asked by useragent as HTTP/1.0 responds HTTP/1.1 answer (chunked responses)! It's illegal method! If useragent ask HTTP/1.0 protocol then 1.0 SHOULD BE USED!

Here debug info of HTTP downloading through wget program:

---request begin---
GET /mycelium-com/wallet-ios/zip/master HTTP/1.0
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The wget asks HTTP/1.0 protocol
....
User-Agent: Wget/1.12 (linux-gnu)
Accept: */*
Host: codeload.github.com
Connection: Keep-Alive
Cookie: logged_in=no

---request end---
Запрос HTTP послан, ожидается ответ...
---response begin---
HTTP/1.1 200 OK
^^^^^^^^^^^^^
Connection: Keep-Alive
Transfer-Encoding: chunked
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
This header should be used only for HTTP/1.1 user agents!

TO SEE RFC:

https://tools.ietf.org/html/rfc2616#page-25

A server which receives an entity-body with a transfer-coding it does
   not understand SHOULD return 501 (Unimplemented), and close the
   connection. A server MUST NOT send transfer-codings to an HTTP/1.0
   client.

This behavior causes a lot of problems for installing tools in all world!

Best regards, Perlover

**Comment by daften** [comment]
I just got this response from github, for us it seems fixed ATM:
Hi Dieter,

Sorry for the trouble.

We received a report of this a few days ago and as far as I can see we pushed out a fix for this.

Could you test it it out and let me know if you still have issues?

Thanks
Stacey

**Comment by Perlover** [comment]
Hi,
Yes, now it was fixed!
I checked two different repositaries in github - now everything is fine!
Thanks!
Best regards, Perlover
