### ISSUE TITLE
https://github.com/isaacs/github/issues/699

### ISSUE THREAD

**Issue by cyberhck** [dear-github/dear-github#223]
We really really need this one, Private GitHub Pages is really useful for many cases, please make it happen.

**Comment by muescha** [comment]
Clickable Link: https://github.com/isaacs/github/issues/699

**Comment by muescha** [comment]
Why you close the issue? Is there a solution available?

**Comment by cyberhck** [comment]
I'm sorry, my bad, Looked like dear-github isn't really looked into by github, and this was duplicate of isaacs/github#699 thought closing it would be okay, do you want it reopened?

**Comment by cyberhck** [comment]
actually, I'm already kind of solving this. First I'm making sure that my pages aren't indexed by google.
Then every time I create a create a PR, I build my docs, then create a directory on gh-pages branch, with a totally random string, maybe `md5(time())` and then I comment on the very same PR to show where the docs can be seen.

This way it works like unlisted, if you want to share, you can give the link, but one would have to guess.

Index.html just shows 404, and whenever I merge to master, I create a directory /master/<random hash> then commit this to master automatically from travis.
