### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by xoviat** [dear-github/dear-github#225]
![image](https://cloud.githubusercontent.com/assets/15351036/21534218/715402c2-cd29-11e6-89de-293b77ff9738.png)

Should be "were made"

**Comment by mariotacke** [comment]
Looks like this was fixed already: 
![image](https://cloud.githubusercontent.com/assets/4942019/22227371/c963be8e-e17f-11e6-8517-4135d6d17d0d.png)
