### ISSUE TITLE
Repo search does not search topics / tags

### ISSUE THREAD

**Issue by avindra** [dear-github/dear-github#233]
I would expect this search:

![screen shot 2017-01-31 at 5 32 40 pm](https://cloud.githubusercontent.com/assets/126848/22487428/4f631a5a-e7db-11e6-8c41-a7ddc7b39434.png)

To search the new "topics" feature on repos, but it does not

**Comment by Mottie** [comment]
You can type in the `topic:` filter manually to make it work... e.g. `topic:java` would narrow your search down on Facebook: https://github.com/facebook?utf8=%E2%9C%93&q=topic%3Ajava

Try out [this search autocomplete userscript](https://greasyfork.org/en/scripts/28592-github-search-autocomplete) to make searching with filters easier.
