### ISSUE TITLE
Allow referencing to assignees and reviewers in pull request description/comments

### ISSUE THREAD

**Issue by xserrat** [dear-github/dear-github#239]
It would be interesting to put to allow the possibility to refer to Pull Request assignees or reviewers using the reserved tags: `@assignees` and `@reviewers`.

This feature could be useful when you are waiting to a final code review to merge de PR and all the reviewers/assignees need to know your comment.

Thank you so much and good job!

**Comment by koenpunt** [comment]
They are assigned, so should already get the notification, right?

**Comment by xserrat** [comment]
Yes, that's right. It could not make sense... 👍

**Comment by dkvaravo** [comment]
How about reminding all of them though?

**Comment by ron-mesh** [comment]
merging this PR and opening another one for FF protection (can't work on this one because Jira is already done)
