### ISSUE TITLE
Revert The dark nav and the change in color palettes

### ISSUE THREAD

**Issue by ickc** [dear-github/dear-github#240]
There's a lot of comments on the internet on the dark nav being distracting. I found there's no open issue here so I would just open this.

The other issue I don't see people mentioning is the change in color palettes. In particular, the green color has been changed recently. In these couple of days, I realized the green is slightly off. I was thinking my monitor being mis-calibrated, or perhaps was using a different profile. But everything else is fine, so I figure it is GitHub that has changed.

The change change is very distracting. If GitHub want to improve the UI, make significant change, e.g. don't use green at all. If you change the hue slightly, it distracts us in the way that we think something is wrong but can't tell exactly what's that.

Probably the blue has changed a bit too, but not as obvious.

**Comment by koenpunt** [comment]
This is very subjective; like for me the green is fine, but the overall blue tint makes it look like my monitor is broken.

**Comment by ickc** [comment]
It is **not about which color looks better, that's always going to be subjective**.

The point is, they **changed the colors only very slightly. That subtle change makes your brain things something is off**. In the case that people calibrate their monitor (I know not all of you do this), it makes us feel that the calibration is off or a wrong profile is used.

So I reiterate my point that if they think the color palette should be improved, they should be making obvious change, not subtle change like this. And then people are always going to dislike big change, so you should give us options (say in settings > themes). That's what happened immediately after the nav bar becomes dark. People complained that (google this) the contrast is distracting, and some others ask for a choice between dark theme (not only the nav but everything) and light theme (original).

I am also interested on what that sad face emoji means. Are you sad about the change, or are you thinking this issue is unneccessary and sad about it.

**Comment by nick-nyllabs** [comment]
@ickc I slapped together a quick theme for the chrome Stylish plugin ("2015GitHub"), approximating as best I can the navbar color theme. Small change for now but will maintain and improve. If/when full palette can be found, I will update, and further welcome [contributions](github.com/nickpalenchar/2015GitHub-Stylish).

![image](https://cloud.githubusercontent.com/assets/22062084/23802835/92383cba-0582-11e7-9d37-6e424ccc3773.png)

**Comment by ickc** [comment]
I think you started this when they first change the nav into a dark theme? By the way, the "contributions" link is broken.

What I don't like is how gitHub handle this is — when they first changed the nav into dark, they promised on Twitter that this will be reverted. But rather than reverting it, they did more questionable changes.

And I can certainly see they are "winning" this. Because virtually no people are complaining about the new color theme, and for those who complain (me), they complain about the subtle change that can causes confusion, which will fades away quickly as time passes. And they "win" by not doing any time during this period of time.

Since I'm not positive this issue will be resolved, and there are 2 sad faces who doesn't even both to explain, I'm going to close this. But I still condemn GitHub on how this is handled and I'm no doubt they are wrong.
