### ISSUE TITLE
Update the project?

### ISSUE THREAD

**Issue by slavafomin** [dear-github/dear-github#248]
Hello!

Is this project is still maintained?

The letter in README looks outdated.

Here's the issue I'm interested the most: https://github.com/dear-github/dear-github/issues/74#issuecomment-295453716

Please consider updating the project and adding it to an open letter.

Thank you for your effort!

@thejameskyle what do you think?

**Comment by thejameskyle** [comment]
We're not ever changing the original letter

**Comment by slavafomin** [comment]
@thejameskyle could you elaborate please?

How do you make further propositions then?

Maybe we could create a list of most wanted features and add it to the README?

**Comment by thejameskyle** [comment]
That is not the purpose of this letter, I will not be doing that

**Comment by slavafomin** [comment]
@thejameskyle what is the purpose of it?

**Comment by thejameskyle** [comment]
A place to host the original contents of the letter, GitHub's reply, and the signatures

**Comment by slavafomin** [comment]
So if you want to promote new features you would suggest to create another repository?
