### ISSUE TITLE
automatically move closed issues to done in github projects

### ISSUE THREAD

**Issue by maxheld83** [dear-github/dear-github#250]

**Comment by rosslh** [comment]
Opt out? But yeah, I'd like this feature.

**Comment by earonesty** [comment]
And the other way around

**Comment by Timmitry** [comment]
And move issues from "Todo" to "In progress" when a PR references it by 'Fixes #...' 😃

**Comment by clarkbw** [comment]
This is possible with project automation 👉 https://help.github.com/articles/configuring-automation-for-project-boards/

**Comment by rahul-ahluwalia** [comment]
I wish the other way around would also work, I.e. dragging an issue to Done in a project should close the issue, or at least provide a setting that would enable it to do so.

**Comment by gpadak** [comment]
Hi :wave: I see that https://github.com/dear-github/dear-github/issues/250#issuecomment-391561529 looks like it's being tracked in https://github.com/dear-github/dear-github/issues/284. Since @clarkbw mentioned the changes to project board automation in https://github.com/dear-github/dear-github/issues/250#issuecomment-372824912, should this issue be closed?

**Comment by vineetsetia** [comment]
This will be really awesome, please let us know when this is available

**Comment by maxheld83** [comment]
sorry, this has actually been a feature for some time now. My bad.

**Comment by vineetsetia** [comment]
Can you please point us to the documentation on how to use it ?

**Comment by clarkbw** [comment]
Project automation https://help.github.com/en/articles/configuring-automation-for-project-boards

**Comment by Saf1997** [comment]
Our project has 2 repos in it. I tested the automation (moving 'in progress' card to 'done') in 1 repo and it worked. But in the main repo our team use for our codebase, the automation doesn't seem to work even when we write 'closes #....' in the PR comment (linking issue number to the PR). 

I've been trying to find out if this has something to do with how the 2 repos we have are set up or are the autolinking rules defined in the overall project and are the same for all repos in a project?

**Comment by sebastianvitterso** [comment]
If anyone sees this in 2024, the guide is simple (this is for non-classic projects)

1. In your project, hit the three dots in the top right, and then "Workflows"
![image](https://github.com/dear-github/dear-github/assets/37065184/2b50b079-1944-4b01-867d-f0e2d7309379)

2. The bottom-most workflow "Auto-close issue" allows you to set a project status that when used, also closes the issue.
![image](https://github.com/dear-github/dear-github/assets/37065184/395d7b5f-2dd5-48c6-be5f-dbef41d4cee8)

**Comment by cyberw** [comment]
I love how they fixed auto-close but didn't bother with auto-open if you drag it back to In Progress!? So close to making an actually useful feature...

There's no way to enable  that, right?
