### ISSUE TITLE
Create a collapse all button for hiding files when reviewing diffs

### ISSUE THREAD

**Issue by mitermayer** [dear-github/dear-github#273]
Sometimes the PR can be pretty big and have various file changes and we may want to look and focus on a single file at a time. 

A super awesome workflow would be the ability to hide all the files on the PR this way as we open them we know that they have been already reviewed.

This feature is so important for me that i created my own hack to achieve that by doing some console hacking

```javascript
Array.prototype.slice.apply(document.querySelectorAll('button.js-details-target')).forEach(button => button.click())
```

**Comment by lukehefson** [comment]
Hey! This is [now](https://blog.github.com/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/) a native feature of GitHub via a keyboard shortcut 😄.

**Comment by Berkmann18** [comment]
@mitermayer Seems like it's time to close this issue.
