### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by dragetd** [dear-github/dear-github#282]
Most (all?) of the requests in this repository have been implemented by GitHub. Now, after shouting at GH for weeks, months and years and complaining about the lack of communication and timely updates, it is time not do this ourselves!

The README should reflect that changes were made, eventually list things that should be still addressed or just a thank you for GH.

I would also happily contact @thejameskyle , but I was unable to find a mail address or service I use to contact him. This is why I choose this issue. :)

**Comment by thejameskyle** [comment]
GitHub has done a lot to improve the communication with maintainers/users. This repo is now just an artifact. I think we ought to just leave it alone
