### ISSUE TITLE
Please stop stealing my browser's CTRL+F in the code editor

### ISSUE THREAD

**Issue by tonglil** [dear-github/dear-github#288]
When I am editing code in the web editor, please stop stealing my browser's CTRL+F.

Your CTRL+F is sub-optimal: I have to press CTRL+F every time just to go to the next occurrence.

Please let me browser do the hard work and make searching easy for me again.

**Comment by roryokane** [comment]
I think it is necessary for the code editor to steal <kbd>Ctrl</kbd>+<kbd>F</kbd>. The code editor does lazy rendering of only the lines visible on the screen. This is a useful feature that allows you to edit large files without slowing down the browser. But it has the implication that the browser’s <kbd>Ctrl</kbd>+<kbd>F</kbd>, which only searches through rendered elements, would not find text in lines that are offscreen.

The editor already has a key binding for going to the next occurrence: <kbd>Ctrl</kbd>+<kbd>G</kbd>. This is based on the <kbd>⌘</kbd><kbd>F</kbd>/<kbd>⌘</kbd><kbd>G</kbd> convention on macOS. Still, it is a valid request that the editor also bind the <kbd>F3</kbd> key to “next search result” on Windows and Linux.

GitHub’s web editor is powered by the [CodeMirror](https://github.com/codemirror/codemirror), which is open-source. I am not sure whether adding the <kbd>F3</kbd> key binding should be changed within CodeMirror or within GitHub’s customization of CodeMirror’s key bindings. I do see that the demo editor on [codemirror.net](https://codemirror.net/) does not bind <kbd>Ctrl</kbd>+<kbd>F</kbd> to anything.

**Comment by 414owen** [comment]
Would it not be better to let the browser decide when to render (lazily?) That way we could get the normal, expected control-f behaviour.

I have a problem with the built-in editor auto-pasting my clipboard into the search field.

**Comment by lsh-0** [comment]
Still an issue 2023-04-25. Don't steal ctrl-f, please. At least give us a way to opt-out/opt-in to this behaviour.

**Comment by Yetoo1** [comment]
Stop stealing and tracking my data when I want to search a page on my local client ffs github. @tonglil why did you close this?
