### ISSUE TITLE
Allow case changes in same name

### ISSUE THREAD

**Issue by spikespaz** [dear-github/dear-github#297]
Dear Github:

&nbsp;&nbsp;&nbsp;&nbsp;The title is ambiguous, I know. Let me clarify.

When going into repository settings, and changing the capitalization of some letters, there is an error saying that you already own a repo with that name.

I propose that changing the case of some letters in the titles be allowed as the only change. The current workaround is to save the name with a slight modification and cave it again with the capitalization and modification changed/removed.

Just a QOL type issue, hope it gets looked into.

*-- spike*

**Comment by clarkbw** [comment]
This is a bug and we're looking into a fix soon.  Thanks!

**Comment by spikespaz** [comment]
Closing because fixed.
