### ISSUE TITLE
PR author set as commit author after merging

### ISSUE THREAD

**Issue by njirap** [dear-github/dear-github#301]
If someone other than the author of a commit in a branch creates a PR from that branch, when the PR is merged the commit's author will change to the PR creator and remove the original commit author.

Not sure if this is intentional behaviour but doesn't appear right.

**Comment by Berkmann18** [comment]
From what I read regarding commits, the commits will still be pointing to the author of those commits but the merge commit (read the one usually saying "Merged ... from ...") will be the one who merged the PR (not necessarily the PR author).

**Comment by njirap** [comment]
This issue dissapeared. Thanks.
