### ISSUE TITLE
Don't sell to Microsoft

### ISSUE THREAD

**Issue by aensley** [dear-github/dear-github#302]
Please, please, please, please, please don't sell the best part of the Internet to the company that destroyed Codeplex and Skype.

https://www.theverge.com/2018/6/3/17422752/microsoft-github-acquisition-rumors

**Comment by aensley** [comment]
😠

https://blog.github.com/2018-06-04-github-microsoft/

**Comment by Gadgetoid** [comment]
They runs almost 2k repositories including TypeScript, vscode and PXT - https://github.com/microsoft

While I certainly have my doubts, I think pointing to Microsoft's previous failures as an indication for what might become of GitHub is inaccurate.

If anything we should approach this change - if and when it does actually happen - with constructive feedback and gentle prods in what we think is the right direction. Maybe some of those long-standing repository management pain points will finally be solved?

I'm a little apprehensive, and I'm just as guilty of crying foul, but I think we would better serve the interests of all GitHub users by making the conversation "here's how you can improve GitHub" rather than "please don't ruin GitHub."

Perhaps @alichtman would be game for taking "Dear Microsoft" in this direction, rather than the punchy, but vapid one-liner that it is right now: https://github.com/dear-microsoft/dear-microsoft

**Comment by alichtman** [comment]
@Gadgetoid Yeah, that was the idea. I just didn't have time to flesh it out at all. Feel free to open a PR and I'll take a look.

**Comment by Gadgetoid** [comment]
I'm of the opinion - with very little evidence to back it up - that this is more a strategic/cultural move on Microsoft's part, and that the acquisition of GitHub is another string in their bow as they cosy up to the OSS community in the wake of Apple's apparent disdain for productivity (ex Apple user here).

If their end game is to sell more Windows computers to professionals, then their financial incentive is decoupled from any immediate change - for the worse - to GitHub. They may, however, be willing to reinforce their investment and quell the immediate fears with some goodwill gestures toward us- so it seems like an obvious opportunity to guide what those gestures might be.

The projects I manage are very different in size and shape from the typical massively-multi-contributor behemoth that many of GitHub's weak spots affect- with that in mind I'd welcome any and all input for the issues which are most important to people.

Things that matter to me are, by and large, what you might consider community or organisational features such as "Add possibility to associate a new issue with an organization or team"- https://github.com/isaacs/github/issues/765

The ability to fork only specific branches seems to be requested a few times- https://github.com/isaacs/github/issues/1132

I think if anything is obvious from these orgs listing GitHub issues and feature requests is that visibility on features being requested/implemented is terrible and that they need to do better in this respect- https://github.com/isaacs/github/issues/6

In trawling through https://github.com/isaacs/github/issues it became abundantly clear that some of these requests may be already implemented and that I might not know about them :D 

So I guess our first point would be that we need an officially sanctioned place to report points 2 onwards.

**Comment by MarcusTHellams** [comment]
Just don't do it. Microsoft will f$Uk it up.

**Comment by bderiso** [comment]
I'm very interested in fleshing this out, but at this point I've already added a good bit in some work in [my own repo](https://github.com/bderiso/Microsoft-Github-acquisition), so i'm hestinant to do a PR here. I've sent out a few collab invites, let me know your thoughts on how to proceed.

**Comment by aensley** [comment]
https://www.cyberciti.biz/open-source/github-alternatives-open-source-seflt-hosted/

**Comment by aethelwulffe** [comment]
And leave Octocat alone.  The "anime" eyes look dorky.  Evil even.

**Comment by erkinalp** [comment]
sudo close #302.

**Comment by cicina** [comment]
Don't sell please. Don't let them get this close to the source. They plan to shut Linux down, open source down. They want to be the only one. And they are likely to reach their goals easy if you sell this. Fuck them what about Google? They won't keep their shit in Microsoft dirty hands?  Microsoft is gradually taking over, brainwashing people killing Linux preventing users from installing Linux, has 98% of the market, copying Linux ideas running Linux servers, benefiting from open source community. What has Microsoft ever done good? I know what : 
Age of Empires! Nothing else. 
They got literally access to every windows computer in the world, company pc's, personal pc's everywhere. And they are still not finished and want to murder free code. Don't get fooled there is nothing good going to happen with github. Please don't. It's a trap.

**Comment by kirillDanshin** [comment]
Looks like microsoft "developers" press dislike buttons ~every time they need to read~, yea?
C'mon, selling to Microsoft is the worst idea ever invented (after microsoft itself, of course). if you need more money - just get a kickstarter campaign or even fukken ICO. why should I spend thousands bucks on an [opensource project](https://github.com/gramework/gramework)'s lawyers and continuous development and @github just will sell it for $100 to damn microsoft? RLY?

**Comment by bderiso** [comment]
@kirillDanshin maybe you and other whiners should consider that we're simply disliking knee-jerk, outdated, scaremongering and ultimately non-productive, repetitive & reductive points.

If you don't have anything useful to say, please consider NOT SPAMMING everyone else watching this issue.

**Comment by craigbarnes** [comment]
> knee-jerk

https://en.wikipedia.org/wiki/Halloween_documents

> outdated

A leopard can't change its spots...

> please consider NOT SPAMMING

If one post is spamming, you should consider doing the same.

**Comment by aethelwulffe** [comment]
Maybe we will get a good git tracker project onto the Software Conservancy org list one day.  LibreOffice, LibreHealth and lot of the other really good useful and dependable stuff is there...protected and clean.
