### ISSUE TITLE
Add optional dark mode to website

### ISSUE THREAD

**Issue by digitalcraftsman** [dear-github/dear-github#311]
Working in front of a bright monitor under low light conditions, especially at night, can be stressful for the eyes. There's a reason why so many developers prefer dark themes for their text editors and terminals. The same reasons might be also applicable to the GitHub website. The interaction under such conditions could be improved by adding an optional dark mode (similar to Twitter's).

[@StylishThemes/GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark) is a stylesheet that can overwrite the default theme using a browser extension. The dark mode could look like this:

![](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/images/screenshots/after_blue.png)

But a native integration would be preferable.

**Comment by wallyqs** [comment]
This would be great, considering the constant privacy concerns regarding Stylish and extensions usage...

**Comment by kilasuit** [comment]
Echo this as I use both the dark and Wide themes from Stylish which are a huge improvement on eye strain and my productivity - please look to include these in future.

**Comment by digitalcraftsman** [comment]
The dark mode has finally arrived: https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/#dark-mode
