### ISSUE TITLE
README text copy is well intentioned, but tone-deaf.

### ISSUE THREAD

**Issue by lasvegasgamer** [dear-github/dear-github#47]
On one hand, signatories are asking Github to provide you a way to avoid +1 spam, a.k.a people trying to put their name on things to "add support" when they think *their contribution* is the reason it hasn't been done, but not really adding any productive resources to execute on it. The group is unhappy that Github has seemingly ignored your repeated requests for this feature.

On the other, Github has most likely heard these requests, if  "[we've] told you them before". Who knows whether or not they don't have some well founded reason why they haven't implemented these improvements, or even that they agree but aren't able to allocate resources to them.

Instead, OP decided to create a form where people can put their name on things...to add support...in light of what the signatories feel have been ignored repeated requests for something. 

This is arguably enough as far as steps to reproduce, however a recently approved PR now makes this so new signatories are asked to sign a separate Google Doc to avoid the technical/merge conflicts associated with new signatories. It's almost as if the project maintainers are ignoring requests for +1.

**Comment by thejameskyle** [comment]
I don't understand the point of this issue

**Comment by wbeard** [comment]
I'm having a hard time understanding the point. If I had to guess, you're trying to point out the irony that the author has created a way for people to +1 the sentiment and requests in the document.

However ironic, it doesn't invalidate the idea suggested. Not each person who opens an *issue* will think about providing a "me too" mechanism and there won't be a standard way of creating that mechanism even if they think to create one.

**Comment by thejameskyle** [comment]
Most of this was not written by me at all. Doesn't sound like you have anything constructive to say so I'm closing

**Comment by lasvegasgamer** [comment]
I suspect this issue title was too general, but the writeup too specific. To clarify, by posting a letter on Github, but then not making it all clear how people should contribute meaningfully, the letter introduces a possible ideological conflict with Github's mission. Were this all, it's probably not an Issue, but by adding a Google Doc as the only mechanism to contribute, it becomes a binary, signatory or not, creating the exact mechanism (+1) that the letter is arguing against, undercutting its point significantly. I'd argue that was easily fixed (possibilities include e.g. PRs allowed with editorial suggestions, issues to discuss potential Github objections, etc) but that without it @wbeard, it very well could invalidate the idea...or at least that it'd be worth some discussion.

Reasonable parties may disagree, but @thejameskyle I'm not sure how not responding immediately implies I don't have anything to constructive to say. But, since the dear-github user has no public co-owners, I'm not sure why I would know who you are (though you do have a the in your username, so I will assume my mistake). Perhaps it's just the nature of a letter supposedly signed by many people, but quite frankly...who are you? Is that somehow relevant to whether or not one can contribute to the effort?

**Comment by thejameskyle** [comment]
There are a bunch of members of the organization. Also, you are free to open up issues with specific things if you want to.
