### ISSUE TITLE
And GitHub does not send email to me when somebody opened an issue in my repo.

### ISSUE THREAD

**Issue by be5invis** [dear-github/dear-github#62]

**Comment by stevelacy** [comment]
Please check you github notification settings. I had to disable the email notifications.

**Comment by jglovier** [comment]
You need to be watching the repository to receive email notifications.

**Comment by runspired** [comment]
There needs to be a "levels" of email notifications.  Some things should be, some shouldn't be.

**Comment by thejameskyle** [comment]
Yeah check your settings

**Comment by jglovier** [comment]
>There needs to be a "levels" of email notifications. Some things should be, some shouldn't be.

Yeah, def agree that the way notifications works right now could be better in that you either get notifications for all of the things, or none of the things, and finer grained control would certainly be helpful. :+1:

**Comment by be5invis** [comment]
@thejameskyle However there's only one "watching" term, when it is checked GitHub sends tons of notifications to me. There should be a "contributing" term, to restrict this list.
