### ISSUE TITLE
allow me to subscribe to certain aspects of a repo

### ISSUE THREAD

**Issue by fs111** [dear-github/dear-github#68]
I don't want notifications about everything that happens on some repos, but, for instance, only receive a notification, when there is a new release. This should be configurable on a per repo basis.

**Comment by pborreli** [comment]
a notification when a release happens on every starred project would be great.

**Comment by ad-m** [comment]
:+1:

**Comment by wsdjeg** [comment]
notification filter by keywords!!!

**Comment by Stargator** [comment]
:+1: 

A notification only for failed CI builds or failed PR builds. A notification only for new issues, etc

**Comment by maidmaid** [comment]
:+1: the Watch button should look like this :

![expected](https://cloud.githubusercontent.com/assets/4578773/12540055/5ebefd16-c301-11e5-9a8f-9f7b5a3de088.png)

**Comment by tux-00** [comment]
:+1:

**Comment by Croydon** [comment]
I need this badly. There are repositories where I just want to get notified of new commits and/or just new issues and/or PRs, but not every single comment on every single commit, issue and PR. 

If you are following right now a few big projects you get spammed.

**Comment by bhaveshgohel** [comment]
:+1:

**Comment by ShinyChang** [comment]
:+1:

**Comment by laughedelic** [comment]
+1

**Comment by TPS** [comment]
Quite similar to https://github.com/isaacs/github/issues/410
