### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by terminalmage** [dear-github/dear-github#72]
Nearly every issue tracker (JIRA, Google Code, Flyspray, Bugzilla, etc.) can do this, so its lack of availability in Github is puzzling.

Allowing us to prefill issues asking for certain information would ensure more meaningful bug reports, and reduce the amount of time we have to spend asking bug reporters for basic information (software version, platform, steps to reproduce, etc.).

**Comment by terminalmage** [comment]
Welp, I clearly didn't read the bullet points in the README.md.

/me tiptoes away quietly

**Comment by runspired** [comment]
;)
