### ISSUE TITLE
Change Organization name proposal?

### ISSUE THREAD

**Issue by davidwparker** [dear-github/dear-github#79]
I propose to change the name of the organization from "dear-github" to "dear-company" or something more generic like that.

It would be nice if other repositories could be created within the organization such as "dear-apple", "dear-microsoft", "dear-google", etc.

This is just a thought, so no hard feelings if you don't want to deal with the complexities of doing so.

**Comment by thejameskyle** [comment]
I'm not about to open up a channel for corporate shaming, I don't want that to get out of hand.

**Comment by davidwparker** [comment]
@thejameskyle - right on. I didn't think of the original GDoc for "Dear-Github" as corporate shaming, but a way to provide feedback from communities to organizations in a much easier way. Thanks though!

**Comment by thejameskyle** [comment]
I think it would only serve to detract from the point of this letter

**Comment by QuantumInformation** [comment]
Go ahead, could be Rad!
