### ISSUE TITLE
Remove spammers / moderation

### ISSUE THREAD

**Issue by royduin** [dear-github/dear-github#80]
For example 506 and 507, we don't want that kind of submissions.

**Comment by joshmanders** [comment]
Some people just can't be mature. Wonder if it has anything to do with this https://github.com/thank-you-github/thank-you-github

**Comment by jmm** [comment]
And 504. (In case row numbers change: `1/15/2016 10:02:28`.)

**Comment by Studio384** [comment]
And 576, not offensive, but it's still spam.

**Comment by thejameskyle** [comment]
Done, sorry about those people
