### ISSUE TITLE
Was there any response?

### ISSUE THREAD

**Issue by resetnow** [dear-github/dear-github#87]
I mean, we can describe a lot of issues and make a lot of proposals, but did someone from Github actually see this? Was there any reaction?

**Comment by wsdjeg** [comment]
all of you show so many feature request,but who pay for it!

**Comment by resetnow** [comment]
@wsdjeg I didn't quite understand you, sorry. If you meant that these ideas and requests have to be sorted and evaluated — that's this repository is for.

**Comment by wsdjeg** [comment]
sorry for missunderstand

**Comment by passcod** [comment]
Well, it's "[trending](https://archive.is/CgPAa#50%)", at least. That should bring _some_ visibility. Perhaps.

**Comment by Maximilianos** [comment]
First comment: https://news.ycombinator.com/item?id=10904671

**Comment by joshmanders** [comment]
Jono Bacon noticed it right away on HN, but this was all happening over the weekend. Give them time to come up with a proper response.

**Comment by resetnow** [comment]
@Maximilianos thanks!
