### ISSUE TITLE
Setting to make it require your approval to be added to repository.

### ISSUE THREAD

**Issue by joshmanders** [dear-github/dear-github#89]
@sindresorhus just tweeted a web.archive.org link to [this](https://web.archive.org/web/20160119122717/https://github.com/mayuso/JavaDataMining/issues/29) which brings up a good point.

We should be able to set whether or not people can auto add us to repositories as collaborators or if when they do, it requests us to approve it.

**Comment by silverwind** [comment]
Relevant: https://github.com/isaacs/github/issues/463

**Comment by Stargator** [comment]
:+1:

**Comment by sindresorhus** [comment]
Shouldn't be an option. A confirmation should always be required. Just like invitations for organizations.

**Comment by joshmanders** [comment]
I'd prefer the option. Some users such as highly known ones like you would like to require, but people like me who don't see the problem, would rather not be bothered by that extra step.

**Comment by Qix-** [comment]
<img width="927" alt="screen shot 2016-03-30 at 19 12 04" src="https://cloud.githubusercontent.com/assets/885648/14163553/7f907ee2-f6ab-11e5-89a8-bbc4559ba2e4.png">

I don't think Github even understands how their own site works.

**Comment by silverwind** [comment]
This should be fixed with https://github.com/blog/2170-repository-invitations!

**Comment by Qix-** [comment]
Woo! Could someone close this please?

**Comment by joshmanders** [comment]
Your wish is my command.
