### ISSUE TITLE
Link to isaacs/github issue repository

### ISSUE THREAD

**Issue by anko** [dear-github/dear-github#97]
https://github.com/isaacs/github has much more Github wishlist issues tracked (449 of them as I write this, compared with this repository's 28).

I think the readme here should link there, and encourage in people (with `CONTRIBUTING.md`) to post issues there instead, so we'd have them in one place and not scattered about.

**Comment by puzrin** [comment]
Seems dupe of #54

**Comment by anko** [comment]
@puzrin Indeed! Closing.
